name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/container-actions/docker-login@master
      name: Publish to Registry
        with:
          login-server: contoso.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t contoso.azurecr.io/k8sdemo:${{ github.sha }}
          docker push contoso.azurecr.io/k8sdemo:${{ github.sha }}
